name: Terraform Provider Tests

on:
  pull_request:
    paths:
      - '.github/workflows/test.yaml'
      - '**.go'
      - '**.tgz'

permissions:
  # Permission for checking out code
  contents: read

jobs:
  acceptance:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.3.*'
          terraform_wrapper: false
      - run: |
          docker create --name adcm -p 8000:8000 -v /opt/adcm:/adcm/data hub.arenadata.io/adcm/adcm:latest
          docker start adcm
          until $(curl --output /dev/null --silent --head --fail http://127.0.0.1:8000); do
              printf '.'
              sleep 5
          done
          sleep 5
      - run: go test -v -cover ./...
        env:
          TF_ACC: '1'
          ADCM_URL: 'http://127.0.0.1:8000'
          ADCM_LOGIN: 'admin'
          ADCM_PASSWORD: 'admin'

  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - run: go test -v -cover ./...